name: automatizacion

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

#permissions:
 # pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
